// LOGIN
export const LOG_IN_START = "LOG_IN_START"
export const LOG_IN_SUCCESS = "LOG_IN_SUCCESS"
export const LOG_IN_FAIL = "LOG_IN_FAIL"

// SIGN UP
export const SIGN_UP_START = "SIGN_UP_START"
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS"
export const SIGN_UP_FAIL = "SIGN_UP_FAIL"

// SET USER
export const SET_USER = "SET_USER"

// STOP_LOADING
export const STOP_LOADING = "STOP_LOADING"

// LOG_OUT_ACTION
export const LOG_OUT = "LOG_OUT"

// CLEAR_ERROR
export const CLEAR_ERROR = "CLEAR_ERROR"

// FORGET PASSWORD
export const FORGET_PASSWORD = "FORGET_PASSWORD"
